### PR TITLE
Peropteryx 14

### PR DESCRIPTION
**Pull request by joehen**
Just some minor configuration and model changes to get project errors removed

### CODE REVIEW

**Comment by seiferma** [comment]
We already discussed the issue regarding the referenced models in `featureCompletions.ecore` in #17. But your change might work for @dfuchss.
Is there any particular reason for removing the models folders from the build.properties?

**Comment by Scaperista** [comment]
this seemed to be a simple solution for the duplicate representation problem I faced and I just compared the properties to a new created Modeling Project and seemingly this is the new default from Eclipse to only have it as bin include

**Comment by joehen** [comment]
wrong account^^

**Comment by seiferma** [comment]
OK, thats reasonable. Aactually, I have overseen that the models directory is in both `bin.includes` and `source.includes`, which is no good idea anyways.
Most probably, the only questionable point is the change in `featureCompletions.ecore` that @dfuchss should review.

**Comment by dfuchss** [comment]
I'll gonna check the changes in featureCompletions.ecore

**Comment by dfuchss** [comment]
@seiferma @joehen shall we merge it?

**Comment by Scaperista** [comment]
@YvesSchneider any objection to merge?

**Comment by joehen** [comment]
@YvesSchneider any obections to merge?

**Pull request merged**
