### PR TITLE
Fixed unresolvable URI validation error

### PR DESCRIPTION
**Pull request by seiferma**
There is an unresolveable URI validation error in the meta model. From my point of view, this should be a plugin URI but it seems to work when writing it in the same way as the reference to the identifier model. This might be improved later but my first goal was to fix the validation error.

### CODE REVIEW

**Comment by dfuchss** [comment]
@seiferma 
In my case, two errors are displayed. The error with PCM was not displayed until now, the error with the identifier existed before.
image

**Comment by seiferma** [comment]
The error makes sense. Relative URIs work as long as you have the meta models in your workspace. I replaced the URIs with platform resource URIs, which work for my development environment. Could you give it a try? Unfortunately, platform plugin URIs do not work in the development environment.

**Comment by dfuchss** [comment]
@seiferma 
The model seems to be buildable via GenModel; the corresponding models are also loaded via the platform URIs.
The error is still displayed in the development environment.  Is there anything we can do about the errors?

**Comment by seiferma** [comment]
Looks like this warning cannot be fixed properly for both scenarios (working with the meta model installed and having it as project in the workspace). In my opinion, it is not worth spending more effort in fixing this warning.

**Pull request closed without merging**
